name: GitHub-Profile-3D-Contrib

on:
  schadule:
    -cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v3
      - uses: KevinASaputra/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ KevinASaputra }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
